---
# $Author$
# $Date$
# $Source$

# main file for opsview-plugin

- name: Configure local plug-in support for the Opsview agent
  include_tasks: plugin_config.yml
  tags:
  - configuration
  - opsview
  - opsview-plugin

- name: Deploy and configure local Opsview plug-ins
  include_tasks: plugin_install.yml
  loop:          "{{ opsview_agent_plugins }}"
  loop_control:
    loop_var:    plugin_item
  when:          opsview_agent_plugins is defined
  tags:
  - configuration
  - opsview
  - opsview-plugin
