---
# $Author$
# $Date$
# $Source$

# plugin-install file for opsview-agent

- name: Create the configuration file for plugin {{ plugin_item.name }}
  template:
    src: plugin_cfg.j2
    dest: "{{ opsview_agent_cfg_local }}/{{ plugin_item.name }}.cfg"
    owner: "{{ opsview_agent_user }}"
    group: "{{ opsview_agent_group }}"
    mode: '0644'
    backup: false
  notify: Restart OpsView Agent

- name: Copy the plug-in source for {{ plugin_item.name }} to the plug-in directory
  copy:
    src: "{{ opsview_agent_plugin_source }}/{{ plugin_item.name }}"
    dest: "{{ opsview_agent_plugin_local }}/{{ plugin_item.name }}"
    owner: "{{ opsview_agent_user }}"
    group: "{{ opsview_agent_group }}"
    mode: '0754'

- name: Copy the plug-in sources for {{ plugin_item.name }} to the plug-in directory
  copy:
    src: "{{ opsview_agent_plugin_source }}/{{ item.file_name }}"
    dest: "{{ item.target_dir | default(opsview_agent_plugin_local) }}/{{ item.file_name }}"
    owner: "{{ item.user | default(opsview_agent_user) }}"
    group: "{{ item.group | default(opsview_agent_group) }}"
    mode: "{{ item.file_privs | default('0644') }}"
  loop: "{{ plugin_item.source }}"
  when:
  - plugin_item.source is defined

- name: Create the necessary sudoers entry for {{ plugin_item.name }} if requested
  include_tasks: plugin_sudo.yml
  when:
  - plugin_item.sudo is defined
