---
# $Author$
# $Date$
# $Source$

# agent_local_config tasks file for opsview-agent

- name: Create directory for local plug-in configuration files
  file:
    state:        directory
    owner:        "{{ opsview_agent_user }}"
    group:        "{{ opsview_agent_group }}"
    mode:         0755
    path:         "{{ opsview_agent_cfg_local }}"

- name: Create directory for local plug-in files
  file:
    state:       directory
    owner:       "{{ opsview_agent_user }}"
    group:       "{{ opsview_agent_group }}"
    mode:        0755
    path:        "{{ opsview_agent_plugin_local }}"

- name: Ensure the local plug-in configuration files are included by the agent
  lineinfile:
    dest:        "{{ opsview_agent_cfg_file }}"
    line:        "include_dir={{ opsview_agent_cfg_local }}"
    state:       present
  notify:        Restart OpsView Agent
  ignore_errors: "{{ ansible_check_mode }}"
